Deleting runs

diff --git a/.github/workflows/delete-workflow-run-id.yml b/.github/workflows/delete-workflow-run-id.yml
--- a/.github/workflows/delete-workflow-run-id.yml
+++ b/.github/workflows/delete-workflow-run-id.yml
@@ -28,24 +28,27 @@ jobs:
           IFS=',' read -ra NAMES_ARRAY <<< "$WORKFLOW_NAMES"
 
           for repo in "${repositories[@]}"; do
-              IFS='/' read -r org_name repo_name <<< "$repo"
-              echo "Processing repository: $org_name/$repo_name"
+            IFS='/' read -r org_name repo_name <<< "$repo"
+            echo "Processing repository: $org_name/$repo_name"
 
-              workflows="[]"
-              page=1
-              while : ; do
-                  response=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$org_name/$repo_name/actions/workflows?per_page=100&page=$page")
-                  current_page_workflows=$(echo "$response" | jq '.workflows')
+            workflows="[]"
+            page=1
+            while : ; do
+                response=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$org_name/$repo_name/actions/workflows?per_page=100&page=$page")
+                current_page_workflows=$(echo "$response" | jq '.workflows')
 
-                  if [ "$(echo "$current_page_workflows" | jq 'length')" -eq 0 ]; then
-                      break
-                  fi
+                if [ "$(echo "$current_page_workflows" | jq 'length')" -eq 0 ]; then
+                    break
+                fi
 
-                  # Merge current page workflows with the total workflows
-                  workflows=$(echo "$workflows $current_page_workflows" | jq -s '.[0] + .[1]')
-                  ((page++))
-                  sleep 0.1
-              done
+                # Merge current page workflows with the total workflows
+                workflows=$(echo "$workflows $current_page_workflows" | jq -s '.[0] + .[1]')
+                ((page++))
+                sleep 0.2
+            done
+
+            total_workflows=$(echo "$workflows" | jq 'length')
+            echo "Total workflows in $org_name/$repo_name: $total_workflows"
 
             for workflow_name_input in "${NAMES_ARRAY[@]}"; do
 
@@ -55,33 +58,38 @@ jobs:
                 workflow_id=$(echo "$workflows" | jq -r --arg NAME "$workflow_name_input" '.[] | select(.name == $NAME) | .id') 
 
                 if [ -n "$workflow_id" ]; then
-                  echo "Workflow ID for $workflow_name: $workflow_id"
-                  page=1
-                    while : ; do
-                      # Fetch runs for the current page
-                      response=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$org_name/$repo_name/actions/workflows/$workflow_id/runs?per_page=100&page=$page")
-                      runs=$(echo "$response" | jq -r '.workflow_runs[].id')
+                  echo "Workflow ID for $workflow_name_input: $workflow_id"
+                      all_runs="[]"
+                      page=1
+                      while : ; do
+                          response=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/$org_name/$repo_name/actions/workflows/$workflow_id/runs?per_page=100&page=$page")
+                          current_page_runs=$(echo "$response" | jq '.workflow_runs')
 
-                      if [ -z "$runs" ]; then
-                        break
-                      fi
-                      
-                      echo "Runs for workflow $workflow_name_input (Page $page): $runs"
+                          if [ "$(echo "$current_page_runs" | jq 'length')" -eq 0 ]; then
+                              break
+                          fi
 
-                      for run_id in $runs; do
-                        echo "Deleting run ID: $run_id"
-                        response=$(gh api --method DELETE -H "Accept: application/vnd.github.v3+json" /repos/$org_name/$repo_name/actions/runs/$run_id)
-
-                        if [ $? -eq 0 ]; then
-                          echo "Successfully deleted run ID: $run_id"
-                        else
-                          echo "Failed to delete run ID: $run_id"
-                        fi
-                        sleep 0.1
+                          all_runs=$(echo "$all_runs $current_page_runs" | jq -s '.[0] + .[1]')
+                          ((page++))
+                          sleep 0.1
                       done
-                      
-                      ((page++))
-                    done
+
+                      total_runs=$(echo "$all_runs" | jq 'length')
+                      echo "Total runs for workflow $workflow_name_input: $total_runs"
+
+                      run_ids=$(echo "$all_runs" | jq -r '.[].id')
+
+                      for run_id in $run_ids; do
+                          echo "Deleting run ID: $run_id"
+                          response=$(gh api --method DELETE -H "Accept: application/vnd.github.v3+json" /repos/$org_name/$repo_name/actions/runs/$run_id)
+
+                          if [ $? -eq 0 ]; then
+                              echo "Successfully deleted run ID: $run_id"
+                          else
+                              echo "Failed to delete run ID: $run_id"
+                          fi
+                          sleep 0.1
+                      done
                 else
                   echo "No workflow found with name: $workflow_name in repository: $org_name/$repo_name"
                 fi
